# ┌────────────────────────────────────────────────────────────────────────────+
# │ PXReturnTicket 콘피그 파일입니다.
# │ 불필요한 메시지는 지우거나 해당 라인 앞에 '#'을 붇여서 주석 처리해주세요.
# └────────────────────────────────────────────────────────────────────────────+